services:
  db:
    image: postgres:15-alpine
    container_name: telemetry-db
    environment:
      POSTGRES_USER: telemetryapp_user
      POSTGRES_PASSWORD: postgres # This is the password for the PostgreSQL user
      POSTGRES_DB: telemetry
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U telemetryapp_user -d telemetry" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://telemetryapp_user:postgres@localhost:5432/telemetry
      - POSTGRES_PASSWORD=postgres
    network_mode: host
    volumes:
      - ./app:/app/app
      - ./init_db.py:/app/init_db.py
    restart: unless-stopped

volumes:
  postgres_data:
